language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t yavoritomov/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true yavoritomov/docker-react npm run test